# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class ActionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hihi = channel.unary_unary(
        '/Action/hihi',
        request_serializer=hello__pb2.ActionRequest.SerializeToString,
        response_deserializer=hello__pb2.ActionResponse.FromString,
        )


class ActionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hihi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ActionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hihi': grpc.unary_unary_rpc_method_handler(
          servicer.hihi,
          request_deserializer=hello__pb2.ActionRequest.FromString,
          response_serializer=hello__pb2.ActionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Action', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
